### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/IRCCloud-Dark#4]
I think when all basic styling is done, we should move to 1.0.0. Noteably, I'd like to see the dropdown menus fixed before that happens.

@Mottie would you mind doing a somewhat regular release to userstyles.org once I push 1.0.0? I think every 1-2 weeks would suffice.

**Comment by Mottie** [comment]
Sure, it won't be a problem. The only thing that needs to be done to make it ready to paste into userstyles is removing the body background image, so that block looks lke this:

``` css
  body {
    background-color: #222 !important;
    background-image: /*[[bg-choice]]*/ !important;
    background-clip: border-box !important;
    background-origin: padding-box !important;
    /*[[bg-options]]*/
    /*[[bg-options2]]*/
  }
```
